name: "3 ecosystem install"

on:
  workflow_dispatch:
    inputs:
      SKIP_JAVASCRIPT:
        description: "Skip JavaScript"
        type: boolean
        default: false
  
      SKIP_PYPI:
        description: "Skip PyPi"
        type: boolean
        default: false

      SKIP_RUBY:
        description: "Skip Ruby"
        type: boolean
        default: false

permissions:
  checks: write
  actions: read
  contents: read
  id-token: write

jobs:
  build-javascript:
    if: ${{ inputs.SKIP_JAVASCRIPT != true }}
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
          # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          #api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
      # ============= InvisiRisk Setup End =============
      - uses: actions/checkout@v4
      - run: npm install --no-audit --no-fund

      
  build-pypi:
    if: ${{ inputs.SKIP_PYPI != true }}
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
          # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          #api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
      # ============= InvisiRisk Setup End =============
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt

  build-ruby:
    if: ${{ inputs.SKIP_RUBY != true }}
    runs-on: ubuntu-latest
    container:
      image: ruby:3.3
    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          #api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
      # ============= InvisiRisk Setup End =============
      - uses: actions/checkout@v4
      - run: bundle install
